export const gifts = [
  {
    id: 1,
    title: "Money",
    img: "/images/image 4.png",
    bg: "moneybg",
  },
  {
    id: 2,
    title: "Chocolate",
    img: "/images/image 5.png",
    bg: "chocolatebg",
  },
  {
    id: 3,
    title: "Beach Trip",
    img: "/images/image 6.png",
    bg: "beachbg",
  },
  {
    id: 4,
    title: "Shoes",
    img: "/images/image 7.png",
    bg: "shoebg",
  },
  {
    id: 5,
    title: "Shirts",
    img: "/images/image 8.png",
    bg: "shirtbg",
  },
  {
    id: 6,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
  },
];

export const promisedgifts = [
  {
    id: 1,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Sarah",
    promiseditem: "Nike",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 2,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Sam",
    promiseditem: "Nike",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 3,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Seun",
    promiseditem: "N200,000",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 3,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Bake.Design",
    promiseditem: "N200,000",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 4,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Anon",
    promiseditem: "Macbook M2",
    date: "Promise  due date 04, Dec, 2023",
  },
];
