export const gifts = [
  {
    id: 1,
    title: "Money",
    img: "https://firebasestorage.googleapis.com/v0/b/promise-card-89e6e.appspot.com/o/images%2Fmoney.png?alt=media",
    bg: "moneybg",
  },
  {
    id: 2,
    title: "Chocolate",
    img: "https://firebasestorage.googleapis.com/v0/b/promise-card-89e6e.appspot.com/o/images%2Fchocolate.png?alt=media",
    bg: "chocolatebg",
  },
  {
    id: 3,
    title: "Beach Trip",
    img: "https://firebasestorage.googleapis.com/v0/b/promise-card-89e6e.appspot.com/o/images%2Fbeach.png?alt=media",
    bg: "beachbg",
  },
  {
    id: 4,
    title: "Shoes",
    img: "https://firebasestorage.googleapis.com/v0/b/promise-card-89e6e.appspot.com/o/images%2Fshoes.png?alt=media",
    bg: "shoebg",
  },
  {
    id: 5,
    title: "Shirts",
    img: "https://firebasestorage.googleapis.com/v0/b/promise-card-89e6e.appspot.com/o/images%2Fshirt.png?alt=media",
    bg: "shirtbg",
  },
  {
    id: 6,
    title: "GiftBox",
    img: "https://firebasestorage.googleapis.com/v0/b/promise-card-89e6e.appspot.com/o/images%2Fgiftbox.png?alt=media",
    bg: "giftboxbg",
  },
];

export const promisedgifts = [
  {
    id: 1,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Sarah",
    promiseditem: "Nike",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 2,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Sam",
    promiseditem: "Nike",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 3,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Seun",
    promiseditem: "N200,000",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 3,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Bake.Design",
    promiseditem: "N200,000",
    date: "Promise  due date 04, Dec, 2023",
  },
  {
    id: 4,
    title: "GiftBox",
    img: "/images/image 9.png",
    bg: "giftboxbg",
    promisedby: "Anon",
    promiseditem: "Macbook M2",
    date: "Promise  due date 04, Dec, 2023",
  },
];
